nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['http://localhost:5173','http://localhost:4173']
        allow_headers: ['Content-Type','Authorization']
        allow_methods: ['GET','POST','OPTIONS']
        max_age: 3600
    paths:
        '^/': null